# default
spring:
  profiles:
    active: test
    group:
      prod: prod, auth, common
      local: local, auth, common
      test: test, auth, common

---
# common 환경
spring:
  config:
    activate:
      on-profile: common
  jpa:
    defer-datasource-initialization: true # hibernate가 초기화되기 전 data.sql 실행하는 것을 방지
  #  show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create-drop
  devtools:
    livereload:
      enabled: true
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG
# cors 설정
cors:
  allowedOrigins: 'http://localhost:3000'
  allowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowedHeaders: '*'
  maxAgeSec: 3600

server:
  port: 8080

---
# test 환경
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb # db 주소 고정
  sql:
    init:
      data-locations: classpath:data-for-h2.sql # 시작할때 실행시킬 script
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
# local 환경
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
