name: Java CI-CD with Gradle And Docker
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Build
      - name: Build with Gradle
        run: ./gradlew clean build
      # 도커허브 로그인
#      - name: Login to DockerHub
#        uses: docker/login-action@v2.0.0
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 도커 이미지 빌드 및 도커 허브에 push
      - name: docker image build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t mylog:0.0.1-b .
          docker push ${{ secrets.DOCKER_REPO }}/mylog:0.0.1-b

      # docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: ubuntu
          script: |
            cd ~/mylog/mylog-back
            sudo docker pull ${{ secrets.DOCKER_REPO }}/mylog:0.0.1-b
            sudo docker rm -f $(docker ps -q -f "name=mylog-b")
            docker-compose up -d
            docker image prune -f